name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Ubuntu 환경에서 실행

    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4  # GitHub 리포지토리의 파일을 불러옵니다.

      - name: JDK 17버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17  # Java 17 설치

      - name: application.yml 파일 만들기
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.yml  # application.yml 파일 생성

      - name: 테스트 및 빌드하기
        run: ./gradlew clean build  # Gradle로 빌드

      - name: AWS Resource에 접근할 수 있게 AWS credentials 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2  # AWS 리전 설정
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # GitHub 시크릿에 저장된 AWS 액세스 키
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # GitHub 시크릿에 저장된 AWS 비밀 액세스 키

      - name: ECR에 로그인하기
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2  # AWS ECR에 로그인

      - name: Docker 이미지 생성
        run: docker build -t nhj-server .  # Docker 이미지를 빌드

      - name: Docker 이미지에 Tag 붙이기
        run: docker tag nhj-server ${{ steps.login-ecr.outputs.registry }}/nhj-server:latest  # ECR 레지스트리에 태그 추가

      - name: ECR에 Docker 이미지 Push하기
        run: docker push ${{ steps.login-ecr.outputs.registry }}/nhj-server:latest  # ECR에 이미지 푸시

      - name: EC2에 SSH로 접속하여 Docker 컨테이너 실행
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}  # EC2 인스턴스의 퍼블릭 IP
          username: ubuntu  # EC2 사용자명 (보통 'ubuntu')
          key: ${{ secrets.EC2_PRIVATE_KEY }}  # **EC2 private key** (GitHub 시크릿에 저장된 키)
          script_stop: true
          script: |
            echo "Stopping any running containers..."
            docker stop nhj-server || true  # 이전에 실행 중인 컨테이너 종료
            docker rm nhj-server || true  # 이전 컨테이너 제거
            echo "Pulling the latest Docker image from ECR..."
            docker pull ${{ steps.login-ecr.outputs.registry }}/nhj-server:latest  # 최신 이미지 풀
            echo "Running the Docker container..."
            docker run -d --name nhj-server -p 8080:8080 ${{ steps.login-ecr.outputs.registry }}/nhj-server:latest  # 컨테이너 실행

      - name: RDS와 ElastiCache 환경 설정
        run: |
          echo "Setting environment variables for RDS and Redis..."
          export RDS_HOST=${{ secrets.RDS_HOST }}  # RDS MySQL 호스트
          export RDS_PORT=3306
          export REDIS_HOST=${{ secrets.REDIS_HOST }}  # Redis 호스트
          export REDIS_PORT=6379

          # RDS와 ElastiCache 연결 테스트
          echo "Testing MySQL connection..."
          # MySQL 연결 시도
          mysql -h $RDS_HOST -P $RDS_PORT -u root -p${{ secrets.RDS_PASSWORD }} --connect-timeout=10 -e "SHOW DATABASES;" || { echo "MySQL connection failed!"; exit 1; }

          echo "Testing Redis connection..."
          # Redis 연결 시도
          redis-cli -h $REDIS_HOST -p $REDIS_PORT -t 10 PING || { echo "Redis connection failed!"; exit 1; }